# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs: 
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - id: meta
          uses: docker/metadata-action@v4
          with:
            images: |
              ghcr.io/jerson/oidc-ipd
        - uses: docker/setup-qemu-action@v3
        - uses: docker/setup-buildx-action@v3
        - if: github.event_name != 'pull_request'
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - id: docker_build
          uses: docker/build-push-action@v5
          with:
            push: ${{ github.event_name != 'pull_request' }}
            platforms: linux/amd64,linux/arm64
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
        - run: echo ${{ steps.docker_build.outputs.digest }}
